import { strict as assert } from 'node:assert';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, readdirSync, rmSync, realpathSync, cpSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { lessonState } from '../lib/lesson-state.mjs';
const root=realpathSync(mkdtempSync(join(tmpdir(),'loop-lessons-real-verifier-fixture-')));
const vr=resolve(import.meta.dirname,'../bin/verdict-run.sh'),lessons=resolve(import.meta.dirname,'../bin/lessons.mjs');
const env={PATH:process.env.PATH,LOOP_DIR:'.loop',LOOP_RUN_ID:randomUUID()};
const run=(bin,args,extra={})=>spawnSync(bin,args,{cwd:root,env:{...env,...extra},encoding:'utf8'});
try {
  assert.equal(run('git',['init','-q']).status,0);
  writeFileSync(join(root,'.gitignore'),'.loop/\n');
  writeFileSync(join(root,'implementation.txt'),'broken');
  writeFileSync(join(root,'verify.sh'),'#!/bin/sh\n[ "$(cat implementation.txt)" = fixed ] && exit 0\necho "FAIL: implementation is broken"\nexit 1\n');
  run('git',['add','.']);assert.equal(run('git',['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-qm','fixture']).status,0);
  mkdirSync(join(root,'.loop'));
  const first=run('bash',[vr,'--log','.loop/first.log','--','sh','verify.sh']);
  assert.equal(first.status,1,first.stderr);writeFileSync(join(root,'.loop/first-verdict.txt'),first.stdout);
  const failState=JSON.parse(readFileSync(join(root,'.loop/verdict-state.json')));
  writeFileSync(join(root,'implementation.txt'),'fixed');
  const second=run('bash',[vr,'--log','.loop/second.log','--','sh','verify.sh']);assert.equal(second.status,0,second.stderr);
  const passState=JSON.parse(readFileSync(join(root,'.loop/verdict-state.json')));
  const args=['record','--verified','--signature-file','.loop/first-verdict.txt','--receipt',`.loop/evidence/${passState.receipt_id}.json`,'--failure-receipt',`.loop/evidence/${failState.receipt_id}.json`,'--fix','change implementation value to fixed'];
  const result=run(process.execPath,[lessons,...args]);assert.equal(result.status,0,result.stderr);
  const files=readdirSync(join(root,'.loop/lessons')).filter(f=>f.endsWith('.json'));assert.equal(files.length,1);
  const lesson=JSON.parse(readFileSync(join(root,'.loop/lessons',files[0])));
  assert.equal(lesson.verification.receipts[0].id,passState.receipt_id);
  assert.notEqual(lesson.verification.receipts[0].fix_target_before,lesson.verification.receipts[0].fix_target_after);
  assert.equal(lessonState(lesson,{root}).verified,true,'actual producer seal and receipts are readable');
  const feature=join(root,'.loop/linked-feature');
  assert.equal(run('git',['-c','core.hooksPath=/dev/null','worktree','add','--detach',feature,'HEAD']).status,0);
  const featureEnv={...env,LOOP_RUN_ID:randomUUID()};
  const atFeature=(bin,args)=>spawnSync(bin,args,{cwd:feature,env:featureEnv,encoding:'utf8'});
  const f=atFeature('bash',[vr,'--log','.loop/fail.log','--','sh','verify.sh']);assert.equal(f.status,1);
  writeFileSync(join(feature,'.loop/failure.txt'),f.stdout);
  const fs=JSON.parse(readFileSync(join(feature,'.loop/verdict-state.json')));
  writeFileSync(join(feature,'implementation.txt'),'fixed');
  const p=atFeature('bash',[vr,'--log','.loop/pass.log','--','sh','verify.sh']);assert.equal(p.status,0);
  const ps=JSON.parse(readFileSync(join(feature,'.loop/verdict-state.json')));
  const recorded=atFeature(process.execPath,[lessons,'record','--verified','--signature-file','.loop/failure.txt',
    '--receipt',`.loop/evidence/${ps.receipt_id}.json`,'--failure-receipt',`.loop/evidence/${fs.receipt_id}.json`,'--fix','actual linked-worktree fix']);
  assert.equal(recorded.status,0,recorded.stderr);
  const featureLesson=JSON.parse(readFileSync(join(feature,'.loop/lessons',files[0])));
  assert.equal(lessonState(featureLesson,{root:feature}).verified,true,'genuine linked-worktree learning is valid in its original execution root');
  cpSync(join(feature,'.loop/evidence'),join(root,'.loop/evidence'),{recursive:true});
  assert.equal(lessonState(featureLesson,{root}).verified,false,'same git-common owner is not a receipt transfer approval');
  assert.equal(run('git',['-c','core.hooksPath=/dev/null','worktree','remove','--force',feature]).status,0);
  assert.equal(lessonState(featureLesson,{root}).verified,false,'cleanup cannot silently adopt foreign-worktree receipts');
  console.log('PASS: linked-worktree FAIL/fix/PASS seal is local; copied complete evidence remains unverified in canonical checkout after cleanup');
  console.log('PASS: actual verdict-run receipts + exact stdout hash + git-visible implementation fix -> verified lesson');
} finally {rmSync(root,{recursive:true,force:true});}
